status(r0, clear).
status(r1, clear).
status(r2, clear).
status(r3, clear).
status(r4, clear).
status(r5, clear).
status(r6, clear).
status(r7, clear).
status(r8, clear).
status(r9, clear).
status(corridor, clear).
status(street, clear).
